---

- name: install build-essential
  apt: pkg=build-essential state=installed

- name: download src package
  get_url: url=https://github.com/neilalexander/sigmavpn/archive/{{ sigmavpn_version }}.tar.gz
           dest=/tmp/sigmavpn-{{ sigmavpn_version }}.tar.gz

- name: extract sigmavpn
  shell: tar -xzf /tmp/sigmavpn-{{ sigmavpn_version }}.tar.gz 
         chdir=/tmp/
         creates=/tmp/sigmavpn-{{ sigmavpn_version }}

- name: upload makefile.patch
  copy: src=makefile.patch dest=/tmp/sigmavpn-{{ sigmavpn_version }}/makefile.patch

- name: patch makefile
  shell: patch Makefile makefile.patch -o Makefile.patched
         creates=Makefile.patched
         chdir=/tmp/sigmavpn-{{ sigmavpn_version }}/

- name: build 
  shell: make -f Makefile.patched && make install -f Makefile.patched
         chdir=/tmp/sigmavpn-{{ sigmavpn_version }}
         creates=/usr/local/bin/sigmavpn
  notify:
     - restart sigmavpn
     - setup sigmavpn ip

- name: setup config 
  template: src=sigmavpn.conf dest=/usr/local/etc/sigmavpn.conf
  notify:
     - restart sigmavpn
     - setup sigmavpn ip

- name: upload supervisor config
  template: src=supervisor.sigmavpn.conf  dest=/etc/supervisor/conf.d/sigmavpn.conf 
  notify:
     - restart sigmavpn
     - setup sigmavpn ip

#TODO: using ansible_tun_sigma_p1 like var to check change
- name: force reconfig
  shell: echo "force reconfig ip"
  notify:
     - setup sigmavpn ip
