---
#This playbook setup VPN authentication and accounting service for VPN servers . 
#It will install freeradius server with a mysql backend.

- hosts: auth

  roles:
    - common
    - webserver
    - db
    - auth
    - radius-admin
