---
- hosts: ipsec

  roles:
    - common
    - ipsec-sw
#    - vpnmgr-agent
    - role: l2tp
      when: ipsec_enable_l2tp

    - role: ppp-radiusclient
      when: ipsec_enable_l2tp and l2tp_use_radius
      device_type: l2tp
      radius_servers: "{{ l2tp_radius_servers }}"

    - nat
