---
- hosts: l2tp

  vars:
    if_name: eth0
    public_ip:  ${ansible_eth0.ipv4.address}
    #l2tp_use_radius: false

  roles:
    #- common
    - l2tp

    #setup auth via radius
    - role: ppp-radiusclient
      when: l2tp_use_radius
      device_type: pptp
      radius_servers: ${l2tp_radius_servers}

    #nat role will setup firewall
    - role: nat
      device_type: l2tp
      subnet: ${l2tp_network.subnet}
      mtu: ${l2tp_network.mtu}
