---
- hosts: l2tp

  roles:
    - common
    - openswan 
    - l2tp

    #setup auth via radius
    - role: ppp-radiusclient
      when: l2tp_use_radius
      device_type: l2tp
      radius_servers: "{{ l2tp_radius_servers }}"

    - nat
    #- vpnmgr-agent
