---

- hosts: pptp
#  gather_facts: false
  vars:
    if_name: eth0
    public_ip:  ${ansible_eth0.ipv4.address}

  roles:
    - common
    #nas role will setup firewall
    - role: nas
      device_type: pptp
      subnet: ${pptp.subnet}
      mtu: ${pptp.mtu}
      radius: ${pptp.radius}
      if_name: 'eth0'

    - pptp
