---

- hosts: pptp
#  gather_facts: false
  vars:
    if_name: eth0
    public_ip:  ${ansible_eth0.ipv4.address}
    #pptp_use_radius: false

  roles:
#    - common
    - pptp

    #setup auth via radius
    - role: ppp-radiusclient
      when: pptp_use_radius
      device_type: pptp
      radius_servers: ${pptp_radius_servers}

    #nat role will setup firewall
    - nat
    - vpn-mgr
