---

- name: create working directory
  file: path="{{ l2tp_eth_working_dir }}" state=directory

- name: upload setup script
  template: src=setup_server.sh 
            dest="{{ l2tp_eth_server_setup_script }}"
            mode=755
  notify: 
    - setup l2tp-eth server

