---

# setup base dir
- action: file path=/opt/proxy-frontend/ state=directory
  tags: proxy-frontend

#install shadowsocks
- name: copy shadowsocks
  action: copy src={{ item }}
               dest=/opt/proxy-frontend/{{ item }}
               mode=755
  with_items:
    - ss-redir
    - ss-tunnel
    - ss-local
  tags: proxy-frontend

- name: generate ss-redir config file
  action: template src=config-redir.json
                   dest=/opt/proxy-frontend/config-redir.json
                   mode=755
  tags: proxy-frontend
  notify:
    - restart shadowsocks-redir

- name: generate ss dns tunnel config file
  action: template src=config-dns-tunnel.json
                   dest=/opt/proxy-frontend/config-dns-tunnel.json
                   mode=755
  tags: proxy-frontend
  notify:
    - restart shadowsocks-dns-tunnel

# setup superivosr config

- action: template src=proxy-frontend.supervisor.conf
                   dest=/etc/supervisor/conf.d/proxy-frontend.conf
  tags: proxy-frontend

- action: supervisorctl name={{ item }} state=present
  with_items:
    - shadowsocks-redir
    - shadowsocks-dns-tunnel
  notify:
    - restart shadowsocks-redir
    - restart shadowsocks-dns-tunnel
  tags: proxy-frontend

- action: supervisorctl name={{ item }} state=present
  with_items:
    - shadowsocks-redir
    - shadowsocks-dns-tunnel
  tags: proxy-frontend


#setup firewall
#
- name: generate setup redir script
  action: template src=setup_redir
                   dest=/opt/proxy-frontend/setup_redir
                   mode=755
  notify:
    - setup redir
  tags: proxy-frontend

- name: make sure setup_redir is in rc.local
  action: lineinfile dest=/etc/rc.local insertafter="^#" regexp="/opt/proxy-frontend/setup_redir" line="/opt/proxy-frontend/setup_redir" state=present
  tags: proxy-frontend
