- name: install shadowsocks key
  apt_key: url=http://shadowsocks.org/debian/1D27208A.gpg state=present
  tags:
    - ss-server

- name: add shadowsocks repo
  apt_repository: repo='deb http://shadowsocks.org/{% if ansible_distribution == 'Ubuntu' and ansible_distribution_version|float >= 14.04 %}ubuntu trusty{% else %}debian wheezy {%endif%} main' state=present
  tags:
    - ss-server

- name: install shadowsocks libev
  apt: pkg=shadowsocks-libev state=installed force=yes
  tags:
    - ss-server

- name: make a symbol link to /opt/ss-server/
  file: src=/usr/bin/ss-server dest=/opt/ss-server/ss-server state=link
  tags:
    - ss-server
