---
#install shadowsocks

- name: increase fileno
  lineinfile: dest=/etc/security/limits.conf line="{{item}}" insertbefore="# End of file" state=present
  with_items:
    - "* soft nofile 51200"
    - "* hard nofile 51200"
  notify:
    - reload supervisor
  tags:
    - ss-server

- name: add ulimit in defaults/supervisor
  lineinfile: dest=/etc/default/supervisor line="ulimit -n 51200" state=present
  notify:
    - reload supervisor
  tags:
    - ss-server

# see http://shadowsocks.org/en/config/advanced.html
- name: update sysctl for performance
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present reload=yes
  with_items:
    - {"name" : "net.core.wmem_max" , "value" : 12582912}
    - {"name" : "net.core.rmem_max" , "value" : 12582912}
    - {"name" : "net.ipv4.tcp_rmem" , "value" : 10240 87380 12582912}
    - {"name" : "net.ipv4.tcp_wmem" , "value" : 10240 87380 12582912}
    - {"name" : "net.ipv4.ip_local_port_range" , "value" : 18000    65535}
    #- {"name" : "net.ipv4.netfilter.ip_conntrack_tcp_timeout_time_wait" , "value" : 1}
    - {"name" : "net.ipv4.tcp_window_scaling" , "value" : 1}
    - {"name" : "net.ipv4.tcp_max_syn_backlog" , "value" : 3240000}
    - {"name" : "net.core.somaxconn" , "value" : 3240000}
    - {"name" : "net.ipv4.tcp_max_tw_buckets" , "value" : 1440000}
    - {"name" : "net.ipv4.tcp_congestion_control" , "value" : "hybla"}
    - {"name" : "net.ipv4.tcp_tw_reuse" , "value" : 1}
    - {"name" : "net.ipv4.tcp_fin_timeout" , "value" : 15}
    - {"name" : "net.ipv4.tcp_syn_retries" , "value" : 2}
    - {"name" : "net.ipv4.tcp_synack_retries" , "value" : 2}
    - {"name" : "net.ipv4.tcp_tw_recycle" , "value" : 1}
  tags:
    - ss-server

- name: ensure working dir exists
  action: file path=/opt/ss-server/ state=directory
  tags:
    - ss-server

- include: install_libev.yml
  when: shadowsocks_provider == "libev"

- include: install_python.yml
  when: shadowsocks_provider == "python"

#- name: install shadowssocks
#  action: copy src={{ item }}
#               dest=/opt/ss-server/{{ item }}
#               mode=755
#  with_items:
#    - ss-server
#  notify:
#    - "restart shadowsocks-server {{ name }}"
#  tags:
#    - ss-server

- name: install shadowssocks-server supervisorconfig
  template: src=ss-server.supervisor.conf
            dest=/etc/supervisor/conf.d/ss-server-{{ name }}.conf

  notify:
    - "restart shadowsocks-server {{ name }}"
  tags:
    - ss-server

- name: install shadowssocks server config file
  action: template src=config.json
                   dest=/opt/ss-server/config-{{ name }}.json
                   mode=640
  notify:
    - "restart shadowsocks-server {{ name }}"
  tags:
    - ss-server

- name: make shadowssocks-server is present 
  supervisorctl: name=ss-server-{{ name }} state=present
