---
ipsec_enable_l2tp: true
ipsec_enable_ikev1: true
ipsec_enable_ikev2: true

ipsec_domain: "{{ inventory_hostname }}"
ipsec_bind_ip:  "{{ ansible_default_ipv4.address }}"
ipsec_subnet: 10.7.0.0/24

ipsec_use_radius: false
ipsec_radius_servers:
  - host: 127.0.0.1
    secret: some-radius-secret

ipsec_dns_servers:
   - 8.8.8.8
   - 8.8.4.4

ipsec_psk: ipsecworks
ipsec_cert: ipsec.cert
ipsec_key: ipsec.key

ikev1_users: []

ikev2_users: []
#ikev_users:
#  - username: "user1"
#    password: "pass1"
#  - username: "user2"
#    password: "passw"

ipsec_service_name: "{%if ansible_distribution == 'Ubuntu' %}strongswan{% else %}ipsec{% endif %}"
