---
ipsec_enable_l2tp: true
ipsec_enable_ikev1: true
ipsec_enable_ikev2: true

ipsec_domain: 'vpn.exampel.com'
ipsec_bind_ip:  "{{ ansible_eth0.ipv4.address }}"
ipsec_subnet: 10.9.0.0/24

ipsec_use_radius: true
ipsec_radius_servers:
  - host: 127.0.0.1
    secret: some-radius-secret

ipsec_dns_servers:
   - 8.8.8.8
   - 8.8.4.4

ipsec_psk: ipsecworks
ipsec_cert: ipsec.cert
ipsec_key: ipsec.key

l2tp_bind_ip:  "{{ ansible_eth0.ipv4.address }}"

ipsec:
  psk: l2tpworks

l2tp_network:
  local_ip: 10.9.0.1
  remote_ip: 10.9.0.30-250
  ms_dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1340
  subnet: 10.9.0.0/24

l2tp_use_radius: false

l2tp_radius_servers:
  - host: 127.0.0.1
    secret: some-radius-secret
