---
#openvpn_bind_ip:  "{{ ansible_default_ipv4.address }}"

openvpn_name: 'default'
#openvpn_cred:
#  ca: "{{ lookup('file', inventory_dir + '/cred/openvpn/ca.crt') }}"
#  cert: "{{ lookup('file', inventory_dir + '/cred/openvpn/server.crt') }}"
#  key: "{{ lookup('file', inventory_dir + '/cred/openvpn/server.key') }}"
#  dh: "{{ lookup('file', inventory_dir + '/cred/openvpn/dh1024.pem') }}"

openvpn_mode: 'tls' #static
openvpn_proto: udp
openvpn_port: 1194

#for tls mode 
openvpn_subnet: 10.8.1.0
openvpn_netmask: 255.255.255.0
openvpn_cert_source: "gen" #"upload", "pki"
openvpn_pki_db_path: "/etc/openvpn/pki"
openvpn_pki_password: "2e207cfda4414f55b86e16a26ddf276d"

#openvpn_cert_source: "upload"
openvpn_ca_cert: "ca.cert"
openvpn_server_cert: "server.cert"
openvpn_server_key:  "server.key"
openvpn_dh:  "dh1023.pem"



#for static key mode

openvpn_local_ip: 10.8.1.1
openvpn_peer_ip: 10.8.1.2
openvpn_secret_source: "gen"  #upload
openvpn_secret: 'secret.key'

openvpn_dns_servers:
  - 8.8.8.8
  - 8.8.4.4

openvpn_use_radius: false

openvpn_radius_servers:
  - host: 127.0.0.1
    secret: "some-radius-secret"

openvpn_enable_management: true
openvpn_push_redirect_gateway: true
