---

- name: create venv directory
  file: path=/opt/chinadns state=directory
  tags:
    - chinadns

- name: install chinadns
  pip: name=chinadns state=present virtualenv=/opt/chinadns
  tags:
    - chinadns

- name: setup chinadns server
  template: src=chinadns.supervisor.conf dest=/etc/supervisor/conf.d/chinadns.conf
  notify:
    - restart chinadns-server
  tags:
    - chinadns
