---
pch_name: "localhost"
pch_hostname: 'wpd'
pch_listen_ip: "127.0.0.1"
pch_listen_port: 80

pch_default_proxy: 'socks'
pch_default_mode: 'chnroutes'

pch_proxy_servers:
  - name: socks
    type: "socks5"
    host: "127.0.0.1"
    port: 1080
  - name: http
    type: "http"
    host: "127.0.0.1"
    port: 8123


intranet_addresses:
  - ["127.0.0.0", "255.0.0.0"]
  - ["10.0.0.0", "255.0.0.0"]
  - ["172.16.0.0", "255.0.0.0"]
  - ["192.168.0.0", "255.255.0.0"]
