- name: restart shadowsocks-redir
  action: supervisorctl name=shadowsocks-redir state=restarted

- name: restart shadowsocks-dns-tunnel
  action: supervisorctl name=shadowsocks-dns-tunnel state=restarted

#- name: reload shadowsocks-server
#  action: shell /bin/kill -s HUP `/usr/bin/supervisorctl pid shadowsocks-ridir`

- name: setup redir 
  action: command /opt/proxy-frontend/setup_redir
