---
#vpn server management api

- name: ensure directory used by vpn-mgr exists
  action: file path={{ item }} state=directory
  with_items:
    - /opt/vpn-mgr
    - /opt/vpn-mgr/env
  tags: vpn-mgr


- name: install some vpn-mgr dependecy
  action: pip name="git+https://github.com/ftao/python-ifcfg.git#egg=ifcfg" virtualenv=/opt/vpn-mgr/env virtualenv_site_packages=yes extra_args="-e"
  notify:
    - restart vpn-mgr-web
  tags: vpn-mgr

- name: install vpn-mgr
  action: pip name="git+https://github.com/ftao/vpn-mgr#egg=vpn-mgr" virtualenv=/opt/vpn-mgr/env virtualenv_site_packages=yes extra_args="-e"
  notify:
    - restart vpn-mgr-web
  tags: vpn-mgr

- name: setup supervisor config
  action: template src=vpn-mgr.supervisor.conf dest=/etc/supervisor/conf.d/vpn-mgr.conf
  notify:
    - restart vpn-mgr-web
  tags: 
    - vpn-mgr
